# Generated by Django 4.2.6 on 2023-10-07 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programm_lang', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='programlang',
            name='created_date_lang',
            field=models.DateField(null=True),
        ),
    ]
