# Generated by Django 4.2.6 on 2023-10-11 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programm_lang', '0002_programlang_created_date_lang'),
    ]

    operations = [
        migrations.AddField(
            model_name='programlang',
            name='actuality',
            field=models.CharField(choices=[('Актуален', 'Актуален'), ('50 на 50', '50 на 50'), ('Стрем', 'Стрем')], default=('Актуален', 'Актуален'), max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='programlang',
            name='video',
            field=models.URLField(null=True),
        ),
    ]
