# Generated by Django 4.2.6 on 2023-10-16 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programm_lang', '0003_programlang_actuality_programlang_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewProgLang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_review', models.TextField()),
                ('rate_stars', models.CharField(choices=[('*', '*'), ('**', '**'), ('***', '***'), ('****', '****'), ('*****', '*****')], max_length=100)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('title_lang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_object', to='programm_lang.programlang')),
            ],
        ),
    ]
